/**
 * Smart-Prediction authorization codes, one pool per purchasable tier.
 *
 *   501 (1K  USDT · 初级 符胚)  → 300 codes (RUNE-E-…)
 *   401 (2.5K USDT · 中级 符源) → 20  codes (RUNE-D-…)
 *   301 (5K  USDT · 高级 符印)  → 30  codes (RUNE-C-…)
 *   201 (10K USDT · 超级 符魂)  → 20  codes (RUNE-B-…)
 *   101 (50K USDT · 联创 符主)  → no code (founders skip the gate)
 *
 * Each connected wallet that owns a node is shown exactly ONE deterministic
 * code from its tier's pool — same wallet always sees the same code.
 */

import type { NodeId } from "@/lib/thirdweb/contracts";

const CODES_501: readonly string[] = [
  "RUNE-E-DTYG-6EVL","RUNE-E-WD6E-UYEG","RUNE-E-HP8E-ACCZ","RUNE-E-L94J-4VEX",
  "RUNE-E-FFKP-49DQ","RUNE-E-JGBA-CNXW","RUNE-E-C7R5-K5XL","RUNE-E-GTKF-GAZG",
  "RUNE-E-HJS5-LFWG","RUNE-E-BTND-ZREY","RUNE-E-YX27-8TQJ","RUNE-E-KQHJ-2J4T",
  "RUNE-E-D9BE-DA6D","RUNE-E-XESQ-B2A8","RUNE-E-XDZT-6KS7","RUNE-E-KJFV-G2DN",
  "RUNE-E-QUGB-TXLP","RUNE-E-WKVM-QCH9","RUNE-E-XNGV-2RNR","RUNE-E-UP88-ZQD6",
  "RUNE-E-QCBE-ERZB","RUNE-E-JJ3U-89TQ","RUNE-E-XPR4-JU7E","RUNE-E-UUBQ-HDDM",
  "RUNE-E-NW93-VQXQ","RUNE-E-39L9-ZA9C","RUNE-E-Q49M-A4HM","RUNE-E-Y43D-K97K",
  "RUNE-E-4SHY-LRYT","RUNE-E-XNVK-955L","RUNE-E-7UZA-FCJT","RUNE-E-NZWE-U2LW",
  "RUNE-E-GB52-XSW2","RUNE-E-42HR-B9H3","RUNE-E-HXVC-EMCP","RUNE-E-Q643-D47X",
  "RUNE-E-BM8D-MCNT","RUNE-E-ZTVS-BJEA","RUNE-E-U92W-64YU","RUNE-E-ZA7G-Z66U",
  "RUNE-E-MYLF-YNZP","RUNE-E-QYJ5-EPLF","RUNE-E-EA3C-DBUD","RUNE-E-XTNX-R7R4",
  "RUNE-E-FNNE-RYCY","RUNE-E-FS7D-TJJU","RUNE-E-XD4P-QS55","RUNE-E-CZQT-K4TZ",
  "RUNE-E-TZQS-DFPE","RUNE-E-CE7G-RSPT","RUNE-E-S7EE-4FCC","RUNE-E-QWLK-NP8A",
  "RUNE-E-9MKT-EDDS","RUNE-E-6FXK-ERPH","RUNE-E-LQBL-U4HV","RUNE-E-CVHY-YANR",
  "RUNE-E-TYHH-48KT","RUNE-E-SFRN-D23U","RUNE-E-3W8P-HKMT","RUNE-E-N4CG-HNGE",
  "RUNE-E-GLVB-WCGD","RUNE-E-URKL-Q383","RUNE-E-WJ7W-S27V","RUNE-E-HJ2U-2BWN",
  "RUNE-E-MX9P-66FC","RUNE-E-S27B-HRZL","RUNE-E-5PDT-N4PU","RUNE-E-RF7M-W7JR",
  "RUNE-E-J93T-D2L8","RUNE-E-FKKD-GYYA","RUNE-E-PVFY-YJPZ","RUNE-E-E2V9-7V7A",
  "RUNE-E-ZVUY-LRAW","RUNE-E-KXVZ-5Z3A","RUNE-E-LWJA-FEN9","RUNE-E-9P9W-MFWK",
  "RUNE-E-W8Q5-QKG6","RUNE-E-Y2SA-8ANK","RUNE-E-RY2N-D979","RUNE-E-5L2Y-GU6E",
  "RUNE-E-JQKD-69RG","RUNE-E-N2TK-B9UK","RUNE-E-997N-CJ87","RUNE-E-K69L-5LEH",
  "RUNE-E-QGUD-229D","RUNE-E-2X6D-XG57","RUNE-E-MYC6-TEA9","RUNE-E-JTPT-KZB4",
  "RUNE-E-3HQ7-A2KE","RUNE-E-ZRR6-LQB5","RUNE-E-QF6D-DNMW","RUNE-E-YPR9-7YFP",
  "RUNE-E-LRS9-KZ4R","RUNE-E-VUPF-467Y","RUNE-E-98K8-BC6E","RUNE-E-23Y5-M3BX",
  "RUNE-E-EBHX-9DUP","RUNE-E-ZR7Y-7U5F","RUNE-E-ZZRF-PFXB","RUNE-E-UFWN-XJV9",
  "RUNE-E-X9BB-QL2S","RUNE-E-QPJG-LDXT","RUNE-E-CH9B-B6SW","RUNE-E-6BT9-TY64",
  "RUNE-E-MN63-8VYW","RUNE-E-3EV8-X376","RUNE-E-R7NG-F3PP","RUNE-E-6NNF-4F4J",
  "RUNE-E-SKK3-WUVA","RUNE-E-7TVG-LYYF","RUNE-E-RVRL-S347","RUNE-E-XQ7Z-9AWG",
  "RUNE-E-KRSA-A89W","RUNE-E-3YQM-9SBA","RUNE-E-PRBG-B7JF","RUNE-E-4AJN-UGV6",
  "RUNE-E-XU7E-GLRV","RUNE-E-BLNX-SRGU","RUNE-E-XLR6-HQ9C","RUNE-E-PWHG-YZGY",
  "RUNE-E-9HXW-B86B","RUNE-E-2GQB-SN5G","RUNE-E-DEG6-TPZZ","RUNE-E-LWB6-2FWP",
  "RUNE-E-EJTZ-U6VJ","RUNE-E-6LLQ-CU73","RUNE-E-8CQ9-75P9","RUNE-E-N452-QDDD",
  "RUNE-E-FVKU-5F9V","RUNE-E-XSSH-99KZ","RUNE-E-G8ZL-HP7B","RUNE-E-VE2A-NMU8",
  "RUNE-E-M52F-49W7","RUNE-E-TT75-CXZA","RUNE-E-HUZG-8QXC","RUNE-E-YQLE-HWPA",
  "RUNE-E-V98K-RZ3N","RUNE-E-PH64-MVN5","RUNE-E-7BZG-BEEE","RUNE-E-B3WA-B4A8",
  "RUNE-E-LRHN-T9W5","RUNE-E-SZMK-QKA5","RUNE-E-6AC8-H3UT","RUNE-E-2ABV-PYH2",
  "RUNE-E-PQZL-WPJW","RUNE-E-DDJC-L93U","RUNE-E-DJQS-7MXE","RUNE-E-MNXQ-YTDH",
  "RUNE-E-T4ZY-NA8B","RUNE-E-S5Z8-RXDV","RUNE-E-8TDK-6LF2","RUNE-E-W4N6-G6K7",
  "RUNE-E-QT9P-KTN9","RUNE-E-NUY8-U96C","RUNE-E-SSTH-UEXF","RUNE-E-EMGV-46CZ",
  "RUNE-E-LT3T-8ZB4","RUNE-E-6SB5-PHS4","RUNE-E-EDYM-T6EC","RUNE-E-HKKA-Q7AP",
  "RUNE-E-FVAR-LMKS","RUNE-E-EK89-3TFZ","RUNE-E-967J-HFUS","RUNE-E-XSX6-JTPP",
  "RUNE-E-G5R2-Z6EB","RUNE-E-4WG2-KNT9","RUNE-E-XRYR-FSRZ","RUNE-E-HPHJ-XETU",
  "RUNE-E-2B8Y-LV7N","RUNE-E-HXNK-3MCZ","RUNE-E-BQUY-D64S","RUNE-E-ZJJ3-K2KY",
  "RUNE-E-96KG-FRWA","RUNE-E-MCBZ-J8LP","RUNE-E-5VP8-YK53","RUNE-E-2Y6V-Q2Z7",
  "RUNE-E-SF3B-VZTG","RUNE-E-TLLF-KUGZ","RUNE-E-YJA2-B6AP","RUNE-E-LQSH-7DHH",
  "RUNE-E-QZVG-LHA5","RUNE-E-WYRA-86FM","RUNE-E-JSBV-GLLT","RUNE-E-E84W-KET6",
  "RUNE-E-2889-KA68","RUNE-E-4X8T-GADQ","RUNE-E-8YEJ-VLRW","RUNE-E-GTA4-UZT4",
  "RUNE-E-DP9Z-KUBU","RUNE-E-QZR2-HQEB","RUNE-E-NGSB-VY62","RUNE-E-C8SW-DEGW",
  "RUNE-E-63XE-ASRP","RUNE-E-MBDE-4H78","RUNE-E-2KUW-2Z3J","RUNE-E-B6JB-8K9U",
  "RUNE-E-9NWY-V2EF","RUNE-E-BVT9-MYRM","RUNE-E-XAXQ-GYYR","RUNE-E-WHLY-MDQ7",
  "RUNE-E-PH54-7JD3","RUNE-E-38KQ-PBVV","RUNE-E-CGED-MUZB","RUNE-E-2BJW-N88E",
  "RUNE-E-S6NP-99RN","RUNE-E-GUUA-9VJL","RUNE-E-A9GK-JR3L","RUNE-E-AMQ3-L7WB",
  "RUNE-E-6ZT4-ENWK","RUNE-E-LU4Q-7QX8","RUNE-E-F2UT-ULXA","RUNE-E-LUEL-SGL2",
  "RUNE-E-QY3P-R4AG","RUNE-E-X6Z5-BMQM","RUNE-E-ERJ6-ANXQ","RUNE-E-LKNE-KFYT",
  "RUNE-E-ZUXU-N2CM","RUNE-E-9AX8-APF5","RUNE-E-XAWD-8FQE","RUNE-E-XXE3-XL8P",
  "RUNE-E-CP49-G68B","RUNE-E-23BG-2CT7","RUNE-E-EW5P-UQCQ","RUNE-E-NURM-37AR",
  "RUNE-E-2SLG-N445","RUNE-E-RWBZ-ZRGN","RUNE-E-XEQD-P7XY","RUNE-E-KUET-ME3W",
  "RUNE-E-5WXX-VX5W","RUNE-E-UN9U-8LCA","RUNE-E-NY8S-3TC5","RUNE-E-G9JB-2M4J",
  "RUNE-E-Q5UM-S5GP","RUNE-E-DYKE-PMET","RUNE-E-2VKU-CVJX","RUNE-E-Z4U4-VTUV",
  "RUNE-E-DSFD-FHH6","RUNE-E-YYSL-57HU","RUNE-E-L2RN-AQT9","RUNE-E-G2YM-F4AM",
  "RUNE-E-AM5M-R43V","RUNE-E-NVPH-NPJ7","RUNE-E-TJB4-SD6K","RUNE-E-2WVF-6CAZ",
  "RUNE-E-S2X3-TDB4","RUNE-E-C95V-7A64","RUNE-E-35BU-8E5T","RUNE-E-T65E-JY2N",
  "RUNE-E-HDRY-FND9","RUNE-E-QQKN-ZELT","RUNE-E-QRGW-X4F4","RUNE-E-B39Z-2PHC",
  "RUNE-E-A5Z9-VR7A","RUNE-E-LCPZ-UEHX","RUNE-E-YVQE-NFCR","RUNE-E-UHPL-454W",
  "RUNE-E-UAKZ-YPJ6","RUNE-E-4KE7-4GUR","RUNE-E-5MKA-8BM3","RUNE-E-UGX7-26H9",
  "RUNE-E-CVTA-ZFRM","RUNE-E-NA6P-ZW7T","RUNE-E-Q6NZ-FP5E","RUNE-E-HUJB-BU8Y",
  "RUNE-E-52L4-HK2V","RUNE-E-RESS-PYQ5","RUNE-E-57QX-4XDR","RUNE-E-R98S-2UNJ",
  "RUNE-E-ZX96-UA9S","RUNE-E-VPJ8-TRPL","RUNE-E-Y9C5-5WZN","RUNE-E-A79J-E5J3",
  "RUNE-E-H5KX-BN8G","RUNE-E-VJ9T-T3SW","RUNE-E-YDDR-BY3G","RUNE-E-LHG8-WR6U",
  "RUNE-E-C2AG-6YHS","RUNE-E-P55M-RYLR","RUNE-E-EBLB-QJES","RUNE-E-NKJE-9HHM",
  "RUNE-E-BWPY-T2QS","RUNE-E-DJNX-2AEY","RUNE-E-RQDM-KQ27","RUNE-E-PJ4Y-4SKJ",
  "RUNE-E-2DLN-9KZL","RUNE-E-2CPT-X5TA","RUNE-E-QFB3-WRQH","RUNE-E-XGM4-CFWD",
  "RUNE-E-956C-8XBW","RUNE-E-AUEX-9G2F","RUNE-E-3CEE-GRPT","RUNE-E-AZZV-Z2MX",
  "RUNE-E-26FR-SGTC","RUNE-E-ZGWV-SKUN","RUNE-E-XW3J-6FEP","RUNE-E-DKLX-LQ7W",
  "RUNE-E-UCTU-BDHL","RUNE-E-TSJH-A9S7","RUNE-E-YT8E-M85Q","RUNE-E-WH2F-B9A3",
];

const CODES_401: readonly string[] = [
  "RUNE-D-DHCY-J3PR","RUNE-D-CRVT-NWLB","RUNE-D-NECD-HNED","RUNE-D-THR6-FW6A",
  "RUNE-D-KJV5-AHY9","RUNE-D-ZSB6-N6B7","RUNE-D-CUJ9-W69K","RUNE-D-S8QT-YT3F",
  "RUNE-D-WYA8-GYJF","RUNE-D-97QA-BAG4","RUNE-D-PWYD-JJUC","RUNE-D-QFBV-AAXE",
  "RUNE-D-RRAT-QXAY","RUNE-D-N7GJ-52GZ","RUNE-D-GBSP-XNBF","RUNE-D-QFKR-3HK3",
  "RUNE-D-K5EA-4DKT","RUNE-D-3UTN-JKBB","RUNE-D-STXQ-2E7T","RUNE-D-YEZM-9LYZ",
];

const CODES_301: readonly string[] = [
  "RUNE-C-9LJH-4XRD","RUNE-C-A3ZA-BRYW","RUNE-C-4L67-9GJ3","RUNE-C-G9W3-RM6C",
  "RUNE-C-WYP2-LYSF","RUNE-C-Q4FL-99XE","RUNE-C-XGSJ-K5WY","RUNE-C-58VN-5BZL",
  "RUNE-C-544A-848X","RUNE-C-WDTS-ZWAN","RUNE-C-QZS7-QJ3C","RUNE-C-UMR5-49GH",
  "RUNE-C-F9VH-E5XD","RUNE-C-ESBX-N9TA","RUNE-C-2LNR-2UZ2","RUNE-C-BXZH-L85Q",
  "RUNE-C-Q9WA-PEXL","RUNE-C-4V95-WQ7W","RUNE-C-24JQ-VCCD","RUNE-C-XVTE-VQTK",
  "RUNE-C-WEVK-PBJJ","RUNE-C-5CPC-BJVE","RUNE-C-9DSN-4GHP","RUNE-C-QEQ2-G5HK",
  "RUNE-C-FB9L-NFMK","RUNE-C-HPXV-TAPF","RUNE-C-95KV-TDDW","RUNE-C-SNGH-6H4N",
  "RUNE-C-J6SR-J6GD","RUNE-C-W6CW-SPNS",
];

const CODES_201: readonly string[] = [
  "RUNE-B-MXK7-4WY8","RUNE-B-Y976-X2E4","RUNE-B-JY2Y-4FEX","RUNE-B-ZL22-LY6Y",
  "RUNE-B-8TLW-47G6","RUNE-B-2BJD-LKUG","RUNE-B-F4HS-WEYU","RUNE-B-6MVK-Z228",
  "RUNE-B-YKEU-2QAA","RUNE-B-PPK4-2FQH","RUNE-B-53WY-CM4F","RUNE-B-HMGA-S2UG",
  "RUNE-B-ZD6T-9Y65","RUNE-B-9ETJ-ZXQP","RUNE-B-RR84-WPFC","RUNE-B-VNWY-QK9E",
  "RUNE-B-ZSZ7-K54Y","RUNE-B-ZCQU-33HD","RUNE-B-M86Z-9MUM","RUNE-B-WAQA-LSQA",
];

/** All pools keyed by nodeId. 101 (FOUNDER · 50K) intentionally has no pool. */
export const AUTH_CODE_POOLS: Partial<Record<NodeId, readonly string[]>> = {
  501: CODES_501,
  401: CODES_401,
  301: CODES_301,
  201: CODES_201,
};

/** Tier IDs that gate behind a code. 101 is excluded by design. */
export const CODE_GATED_TIERS = [501, 401, 301, 201] as const;

// 用户端运行时的"我钱包绑了哪条码"现在走 `usePredictionCode` → Supabase
// `rune_auth_codes` 表（assigned_to = wallet）。旧的 djb2 哈希分发函数
// 已删除——分发由管理员手动绑定，码与钱包是显式 1:1 映射，不再依赖客
// 户端推导。AUTH_CODE_POOLS 仍保留是因为 admin 的 AuthCodeManager UI 还
// 用静态池铺占位行；下一轮把那条也切到 DB 读后即可整文件移除。
